---
# - name: firewalld tasks for RedHat based systems
#   include: RedHat.yml
#   when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat" 

- name: firewalld tasks for Debian based systems
  include: Debian.yml
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian" 